### PR TITLE
Add performance optimization directory page and a page on optimizatio…

### PR DESCRIPTION
**Pull request by WilliamParker**
…n by using hash joins

### CODE REVIEW

**Comment by WilliamParker** [comment]
I'll want to look over this again myself before merging, especially to make sure there aren't any factual errors.  I wrote a Gist that shows how to validate the behavior of nested "failed join bindings" that I describe at the end of the hash-joins page I added in this PR. https://gist.github.com/WilliamParker/f2c753c0a2f58c8abbb4444ecadf124b

**Comment by WilliamParker** [comment]
I am attaching a PDF of the way this looks in the browser for convenience.  This looks good to me now. @rbrush I did wonder if you've ever thought about changing the behavior I describe in the latter parts of this where we essentially "lose" a hash join.  It isn't obvious what one could do to change it though - one could walk the code forms, but simply replacing code inside a user-provided constraint that could rely on the return value seems like it would be dangerous.

[hash_joins.pdf](https://github.com/cerner/clara-site/files/778436/hash_joins.pdf)

**Comment by rbrush** [comment]
This documentation looks good to me; +1 to merge.

As for the nested unification behavior, I'm open to handling the example you added to the documentation and things like it, but I'd be hesitant to add much in the line of guarantees here. My reasoning is that the general case of nested expressions gets tricky. Even things as simple as

```clj
(not (= location ?location))
```

obviously wouldn't use notification. So the best we could do is parse the expression and find unifications for some subset of them, being cautious as to potentially breaking the semantics. 

To be honest, I think the current behavior is the simplest thing for our users to understand, as opposed to having to know non-trivial rules about what nested unifications can be used and what can't. The above examples are simple, but what about the unification nested five layers deep, which may or may not be in an expression that can be transformed to a hash join? If a user wants to be sure about hash joins, just putting them at the top level seems like the best practice.

I'm open to discussion on this topic, but that's my current rationale.

**Comment by WilliamParker** [comment]
Consistently putting hash joins at the top level as constraints seems simpler to me as well.  I don't see a way to handle the manipulation of arbitrary code forms in a transparent and easy to understand way.

**Pull request merged**
