### PR TITLE
Update truthmaint.md

### PR DESCRIPTION
**Pull request by davidrupp**
Typos

### CODE REVIEW

**Comment by rbrush** [comment]
Alright, got these merged (and slightly embarrassed about the number of typos in there). Thanks for the pull requests!

**Comment by davidrupp** [comment]
Happy to contribute. Clara is really cool; thanks for building it.

In case you're wondering why all the sudden scrutiny -- I'm evaluating
Clara for use on a project at Amazon, but EPL can be a problem. Would you
consider multi-licensing? I can give you examples of blessed licenses; MIT
is one that I know of.

You can contact me at david [at] ruppworks [dot] com if you'd rather
discuss this off-list.

**Comment by rbrush** [comment]
Sure, I'm fine with adding MIT as a dual license. I had just used the EPL since that's what Clojure itself uses.

**Comment by davidrupp** [comment]
I think a lot of Clojure lib authors do that. Don't do anything yet on my
account; I'll let you know if it's something I'm going to press forward
with. I'd hate to make you incur that hassle if you don't otherwise need
to. Thanks for being willing to consider it!

**Pull request merged**
