### PR TITLE
Add page for the :fact-type-fn and :ancestors-fn options

### PR DESCRIPTION
**Pull request by WilliamParker**

### CODE REVIEW

**Comment by WilliamParker** [comment]
I'll plan to merge this around the end of the day tomorrow (US Central time) if nobody sees any problems.

**Comment by MrMikeRodriguez** [comment]
The only recommendation I have is to use markdown on the Clojure Symbol and Keyword literals within the text bodies.  This is just the typical conventions.

I tend to just put it on ClassNames too.

e.g.
`:my-keyword`, 'some-rule-name`, `SomeClass`

If you are against this, I'll leave it to your own judgement.

**Comment by mrrodriguez** [comment]
The only recommendation I have is to use markdown on the Clojure Symbol and Keyword literals within the text bodies.  This is just the typical conventions.

I tend to just put it on ClassNames too.

e.g.
`:my-keyword`, `some-rule-name`, `SomeClass`

If you are against this, I'll leave it to your own judgement.

**Comment by WilliamParker** [comment]
Is this the look you're suggesting?
image

To my eye that is pretty visually distracting from the prose, mainly the change in background color, but if others find it more readable I don't mind too much.  I can't actually recall seeing that in any docs, do you know of any examples offhand?  I'd prefer some type of font difference to call out that this is "code" but I'm not sure what form that should take.

Either way I don't think a minor typographic issue needs to block this.  We can address that later and right now I'd like to get something up fairly soon since we've had a number of people ask about the functionality this page describes recently.

**Comment by mrrodriguez** [comment]
Wow, that is much more bold than I was expecting.  I just thought it'd be a slight difference in font.

>Either way I don't think a minor typographic issue needs to block this. 

I agree.  Nevermind that suggestion then.

The docs look good!

**Comment by rbrush** [comment]
+1. 

My only addition would be to add a comment and link to Clojure's derive function to allow users to easily create their own type relationships with existing facilities.

**Comment by WilliamParker** [comment]
+1 to that @rbrush I've updated the PR accordingly.  Perhaps we should add an example that uses derive to clara-examples later as well.

**Comment by mrrodriguez** [comment]
Good addition.

**Pull request merged**
